#! /bin/sh
### BEGIN INIT INFO
# Provides:          cecd
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Provides cec-client daemon
# Description:       This runs cec-client as a daemon service on port
#                    2600.
### END INIT INFO

# Author: Jason Masker <jason@masker.net>

# Do NOT "set -e"

# PATH should only include /usr/* if it runs after the mountnfs.sh script
PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="cec-client daemon"
NAME=socat
DAEMON=/usr/bin/$NAME
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Load cecd.conf, exit if not proper
[ -r /etc/cecd.conf ] || exit 0
. /etc/cecd.conf
[ -n "$CEC_CLIENT" ] || exit 0
[ -n "$CEC_CLIENT_ARGS" ] || exit 0
[ -n "$CECD_PORT" ] || exit 0

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0
[ -x "$CEC_CLIENT" ] || exit 0

# Load the VERBOSE setting and other rcS variables
. /lib/init/vars.sh

# Define LSB log_* functions.
# Depend on lsb-base (>= 3.2-14) to ensure that this file is present
# and status_of_proc is working.
. /lib/lsb/init-functions

#
# Function that starts the daemon/service
#
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
        start-stop-daemon --test --start --quiet --background --pidfile $PIDFILE --make-pidfile --chuid pi \
                --user pi --name $NAME --exec $DAEMON \
		|| return 1
	start-stop-daemon --start --quiet --background --pidfile $PIDFILE --make-pidfile --chuid pi:pi \
                --user pi --name $NAME --exec $DAEMON \
                -- TCP-LISTEN:$CECD_PORT,reuseaddr,fork EXEC:"$CEC_CLIENT $CEC_CLIENT_ARGS" \
		|| return 2
}

#
# Function that stops the daemon/service
#
do_stop()
{
	# Return
	#   0 if daemon has been stopped
	#   1 if daemon was already stopped
	#   2 if daemon could not be stopped
	#   other if a failure occurred
	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --user pi --name $NAME
	RETVAL="$?"
	[ "$RETVAL" = 2 ] && return 2
	
        start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --user pi --exec $DAEMON
	[ "$?" = 2 ] && return 2
	
        rm -f $PIDFILE
	return "$RETVAL"
}

case "$1" in
  start)
	[ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
	do_start
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  stop)
	[ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
	do_stop
	case "$?" in
		0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
		2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
	esac
	;;
  status)
	status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
	;;
  #reload|force-reload)
	#
	# If do_reload() is not implemented then leave this commented out
	# and leave 'force-reload' as an alias for 'restart'.
	#
	#log_daemon_msg "Reloading $DESC" "$NAME"
	#do_reload
	#log_end_msg $?
	#;;
  restart|force-reload)
	#
	# If the "reload" option is implemented then remove the
	# 'force-reload' alias
	#
	log_daemon_msg "Restarting $DESC" "$NAME"
	do_stop
	case "$?" in
	  0|1)
		do_start
		case "$?" in
			0) log_end_msg 0 ;;
			1) log_end_msg 1 ;; # Old process is still running
			*) log_end_msg 1 ;; # Failed to start
		esac
		;;
	  *)
		# Failed to stop
		log_end_msg 1
		;;
	esac
	;;
  *)
	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
	exit 3
	;;
esac

:
